src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 * @ORM\HasLifecycleCallbacks
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\Column(type="datetime_immutable")
     * @Assert\Type("\DateTimeInterface")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime_immutable")
     * @Assert\Type("\DateTimeInterface")
     */
    private $updated_at;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, inversedBy="posts")
     */
    private $tags;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="posts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="post")
     */
    private $comments;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_approve;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->is_approve = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->removeElement($tag)) {
            $tag->removePost($this);
        }

        return $this;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function updatedTimestamps(): void
    {
        $this->setUpdatedAt(new \DateTimeImmutable('now'));
        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt(new \DateTimeImmutable('now'));
        }
    }

    public function __toString()
    {
        return $this->getTitle();
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    public function getIsApprove(): ?bool
    {
        return $this->is_approve;
    }

    public function setIsApprove(bool $is_approve): self
    {
        $this->is_approve = $is_approve;

        return $this;
    }

    public function getPublishDate(): string
    {
        $now = new \DateTime('now');
        $updatedAt = $this->getUpdatedAt();
        $difference = $now->diff($updatedAt);

        return $difference->format('%d days, %h hours, %m minuts.');
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use App\Entity\Tag;
use KMS\FroalaEditorBundle\Form\Type\FroalaEditorType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Blank;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Type;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'constraints' => [
                    new NotBlank(),
                    new Type('string'),
                    new Length([
                        'min' => 3,
                        'max' => 100
                    ])
                ]
            ])
            ->add('text', FroalaEditorType::class, [
                'froala_language'      => 'fr',
                'constraints' => [
                    new NotBlank(),
                    new Type('string'),
                    new Length([
                        'min' => 3,
                        'max' => 5000
                    ])
                ]
            ])
            ->add('tags', EntityType::class, [
                'class' => Tag::class,
                'multiple' => true,
                'required' => false,
                'choice_label' => 'name',
                'label' => 'Tags',
                'by_reference' => false,
                'attr' => [
                    'class' => 'js-example-basic-multiple',
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostsController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Form\PostType;
use App\Repository\PostRepository;
use Doctrine\ORM\EntityManagerInterface;
use Pagerfanta\Doctrine\ORM\QueryAdapter;
use Pagerfanta\Pagerfanta;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/posts')]
#[IsGranted('IS_AUTHENTICATED_REMEMBERED')]
class PostsController extends AbstractController
{
    #[Route('/', name: 'posts_index', methods: ['GET'])]
    public function index(Request $request, PostRepository $postRepository): Response
    {
        $queryBuilder = $postRepository->getPostsQueryBuilder();
        $pagerfanta = new Pagerfanta(new QueryAdapter($queryBuilder));
        $pagerfanta->setMaxPerPage(8);
        $pagerfanta->setCurrentPage($request->query->get('page', 1));

        return $this->render('posts/index.html.twig', [
            'pager' => $pagerfanta,
        ]);
    }

    #[Route('/new', name: 'posts_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
        $post = new Post();
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $post->setUser($user);
            $entityManager->persist($post);
            $entityManager->flush();

            return $this->redirectToRoute('posts_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('posts/new.html.twig', [
            'post' => $post,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'posts_show', methods: ['GET'])]
    public function show(Post $post, Request $request): Response
    {
        return $this->render('posts/show.html.twig', [
            'post' => $post,
        ]);
    }

    #[Route('/{id}/edit', name: 'posts_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Post $post, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('edit', $post);
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('posts_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('posts/edit.html.twig', [
            'post' => $post,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'posts_delete', methods: ['POST'])]
    public function delete(Request $request, Post $post, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('delete', $post);
        if ($this->isCsrfTokenValid('delete'.$post->getId(), $request->request->get('_token'))) {
            $entityManager->remove($post);
            $entityManager->flush();
        }

        return $this->redirectToRoute('posts_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/posts/_comment_delete_form.html.twig
<form method="post" action="{{ path('comments_delete', {'id': comment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ comment.id) }}">
    <button class="btn btn-sm btn-outline-danger">Delete</button>
</form>

templates/posts/_delete_form.html.twig
<form method="post" action="{{ path('posts_delete', {'id': post.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post.id) }}">
    <button class="btn btn-outline-danger">Delete</button>
</form>

templates/posts/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button formnovalidate class="btn btn-outline-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

{% block javascripts %}
    <script
            src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(function() {
            $('.js-example-basic-multiple').select2({
                tags: true,
                tokenSeparators: [',', ' ']
            }).on('change', function (e) {
                let label = $(this).find("[data-select2-tag=true]");
                if (label.length && $.inArray(label.val(), $(this).val() !== -1)) {
                    $.ajax({
                        url: "/tags/new/ajax/"+label.val(),
                        type: "POST"
                    }).done(function (data) {
                        console.log(data)
                        label.replaceWith(`<option selected value="${data.id}">${label.val()}<option/>`);
                    })
                }
            });
        });
    </script>
{% endblock %}

templates/posts/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Post{% endblock %}

{% block body %}
    <h1>Edit Post</h1>

    {{ include('posts/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-outline-info my-2" href="{{ path('posts_index') }}">back to list</a>

    {{ include('posts/_delete_form.html.twig') }}
{% endblock %}

templates/posts/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Post index{% endblock %}

{% block body %}
    <a class="btn btn-success my-2" href="{{ path('posts_new') }}">Create new</a>
    {% if pager|length > 0 %}
        <div class="row row-cols-1 row-cols-md-3 g-4 mb-5">
            {% for post in pager %}
                <div class="col">
                    <div class="card h-100" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">{{ post.title }}</h5>
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a class="btn btn-outline-primary"
                                   href="{{ path('posts_show', {'id': post.id}) }}">show</a>
                                <a class="btn btn-outline-info"
                                   href="{{ path('posts_edit', {'id': post.id}) }}">edit</a>
                                {{ include('posts/_delete_form.html.twig') }}
                            </div>

                            <p class="card-text">
                                <small class="text-muted">Last updated {{ post.updatedAt|date('d.m.Y') }}</small>
                            <p class="card-text">
                                <a href="{{ path('show_profile', {id:post.user.id}) }}"><small
                                            class="text-muted"><strong>By: </strong>{{ post.user.username }}
                                    </small></a>
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {{ pagerfanta(pager) }}
    {% else %}
        <div>No posts have been posted yet.</div>
    {% endif %}
{% endblock %}

templates/posts/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Post{% endblock %}

{% block body %}
    <h1>Create new Post</h1>

    {{ include('posts/_form.html.twig') }}
    <a class="btn btn-outline-info my-2" href="{{ path('posts_index') }}">back to list</a>

{% endblock %}

templates/posts/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Post{% endblock %}

{% block body %}
    <h1>{{ post.title }}</h1>
    {% for tag in post.tags %}
        <a href=""><span class="badge rounded-pill bg-info text-dark">{{ tag.name }}</span></a>

    {% endfor %}
    <figcaption class="blockquote-footer text-end">
        {{ post.createdAt ? post.createdAt|date('d.m.Y H:i:s') : '' }}
    </figcaption>
    <figcaption class="blockquote-footer text-end">
        <strong>Author: </strong>{{ post.user.username }}
    </figcaption>

    {{ froala_display(post.text) }}

    <a class="btn btn-outline-info my-2" href="{{ path('posts_index') }}">back to list</a>

    <a class="btn btn-outline-success" href="{{ path('posts_edit', {'id': post.id}) }}">edit</a>

    {{ include('posts/_delete_form.html.twig') }}
    <div class="row height d-flex justify-content-center align-items-center my-5">
        <div class="col-md-7">
            <div class="card">
                <div class="p-3">
                    <h6>Comments</h6>
                </div>

                <div class="mt-3 d-flex flex-row align-items-center p-3 form-color">
                    {% if app.user.getAvatar %}
                        <img src="{{ vich_uploader_asset(app.user.avatar) }}" width="50" class="rounded-circle mr-2">
                    {% else %}
                        <img src="https://www.kindpng.com/picc/m/24-248253_user-profile-default-image-png-clipart-png-download.png"
                             width="50" class="rounded-circle mr-2">
                    {% endif %}

                    <form action="{{ path('comments_new', {'post': post.id}) }}" method="post">
                    <textarea required class="form-control" name="body" id="" cols="30"
                              rows="10" placeholder="Add your comment..."></textarea>
                        <button class="btn btn-outline-success" type="submit">Add comment</button>
                    </form>
                </div>
                {% for comment in post.comments %}
                    <div class="mt-2">
                        <div class="d-flex flex-row p-3">{% if comment.user.getAvatar %}
                                <img src="{{ vich_uploader_asset(comment.user.avatar) }}" width="40" height="40"
                                     class="rounded-circle mr-3">
                            {% else %}
                                <img src="https://www.kindpng.com/picc/m/24-248253_user-profile-default-image-png-clipart-png-download.png"
                                     width="40" height="40"
                                     class="rounded-circle mr-3">
                            {% endif %}
                            <div class="w-100">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="d-flex flex-row align-items-center"><span
                                                class="mr-2">{{ comment.user.username }}</span>
                                    </div>
                                    <div>
                                        {{ include('posts/_comment_delete_form.html.twig') }}
                                        {# <small>12h ago</small> #}
                                    </div>
                                </div>
                                <p class="text-justify comment-text mb-0">{{ comment.body }}</p>
{#                                <div class="d-flex flex-row user-feed">#}
{#                                    <span class="wish"> <i class="fa fa-heartbeat mr-2"></i>24</span>#}
{#                                    <span class="ml-3"><i class="fa fa-comments-o mr-2"></i>Reply</span>#}
{#                                </div>#}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}