src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"})
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=2)
     */
    private $gender;

    /**
     * @ORM\Column(type="date")
     */
    private $birthday;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, cascade={"persist"}, mappedBy="user", orphanRemoval=true)
     */
    private $images;

    /**
     * @ORM\OneToOne(targetEntity=Image::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="avatar_id", referencedColumnName="id", onDelete="SET NULL")
     */
    private $avatar;

    /**
     * @ORM\OneToMany(targetEntity=Post::class, mappedBy="user", orphanRemoval=true)
     */
    private $posts;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="user", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=Friendship::class, mappedBy="user", cascade={"remove", "persist"})
     */
    private $friends;

    /**
     * @ORM\OneToMany(targetEntity=Friendship::class, mappedBy="friend", cascade={"remove", "persist"})
     */
    private $friendsWithMe;


    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->posts = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->friends = new ArrayCollection();
        $this->friendsWithMe = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getAge(): string
    {
        $now = new \DateTime('now');
        $age = $this->getBirthday();
        $difference = $now->diff($age);

        return $difference->format('%y years, %m months, %d days old.');
    }


    /**
     * @return Collection
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setUser($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            if ($image->getUser() === $this) {
                $image->setUser(null);
            }
        }

        return $this;
    }

    public function __serialize(): array
    {
        return [
            'id' => $this->id,
            'email' => $this->email,
            'password' => $this->password,
        ];
    }

    public function __unserialize(array $serialized)
    {
        $this->id = $serialized['id'];
        $this->email = $serialized['email'];
        $this->password = $serialized['password'];
        // .....
        return $this;
    }

    public function getAvatar(): ?Image
    {
        return $this->avatar;
    }

    public function setAvatar(?Image $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * @return Collection|Post[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setUser($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->removeElement($post)) {
            if ($post->getUser() === $this) {
                $post->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }
        return $this;
    }

    public function addFriendship(Friendship $friendship)
    {
        $this->friends->add($friendship);
        $friendship->getFriend()->addFriendshipWithMe($friendship);
    }

    public function addFriendshipWithMe(Friendship $friendship)
    {
        $this->friendsWithMe->add($friendship);
    }

    /**
     * @return Collection
     */
    public function getFriends(): Collection
    {
         return $this->friends->filter(function ($u) {
            if ($u->getStatus()){
                return $u->getFriend();
            }
        });
    }

    public function addFriend(User $friend): self
    {
        if (!$this->friends->contains($friend)) {
            $fs = new Friendship();
            $fs->setUser($this);
            $fs->setFriend($friend);
            $this->addFriendship($fs);
        }
        return $this;
    }

    public function removeFriend(Friendship $friend): self
    {
        if ($this->friends->removeElement($friend)) {
            if ($friend->getUser() === $this) {
                $friend->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Friendship[]
     */
    public function getFriendsWithMe(): Collection
    {
        return $this->friendsWithMe->filter(function ($u) {
            if (!$u->getStatus()){
                return $u->getFriend();
            }
        });
    }

    /**
     * @return Collection|Friendship[]
     */
    public function getNotApproveFriends(): Collection
    {
        return $this->friends->filter(function ($u) {
            if (!$u->getStatus()){
                return $u->getFriend();
            }
        });
    }

    public function addFriendsWithMe(Friendship $friendsWithMe): self
    {
        if (!$this->friendsWithMe->contains($friendsWithMe)) {
            $this->friendsWithMe[] = $friendsWithMe;
            $friendsWithMe->setFriend($this);
        }

        return $this;
    }

    public function removeFriendsWithMe(Friendship $friendsWithMe): self
    {

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email')
            ->add('roles')
            ->add('password')
            ->add('username')
            ->add('first_name')
            ->add('last_name')
            ->add('gender')
            ->add('birthday')
            ->add('avatar')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UsersController.php
<?php

namespace App\Controller;

use App\Entity\Friendship;
use App\Entity\User;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Pagerfanta\Doctrine\ORM\QueryAdapter;
use Pagerfanta\Pagerfanta;
use Psr\Log\LoggerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/users')]
#[IsGranted('IS_AUTHENTICATED_REMEMBERED')]
class UsersController extends AbstractController
{
    #[Route('/', name: 'users_index', methods: ['GET', 'POST'])]
    public function index(UserRepository $userRepository, Request $request): Response
    {
        $queryBuilder = $userRepository->getUsersQueryBuilder();
        $pagerfanta = new Pagerfanta(new QueryAdapter($queryBuilder));
        $pagerfanta->setMaxPerPage(4);
        $pagerfanta->setCurrentPage($request->query->get('page', 1));
        return $this->render('users/index.html.twig', [
            'pager' => $pagerfanta,
        ]);
    }

    #[Route('/request/{id}', name: 'send_friendship_request', methods: ['GET'])]
    public function sendFriendshipRequest(User $user, EntityManagerInterface $entityManager): RedirectResponse
    {
        $this->denyAccessUnlessGranted('add', $user);
        $this->getUser()->addFriend($user);
        $entityManager->persist($this->getUser());
        $entityManager->flush();
        return $this->redirectToRoute('show_profile', ['id' => $user->getId()]);
    }

    #[Route('/confirm/{id}', name: 'confirm_friendship', methods: ['GET'])]
    public function confirmFriendship(EntityManagerInterface $entityManager, Friendship $friendship): RedirectResponse
    {
        $fs = new Friendship();
        $fs->setUser($friendship->getFriend());
        $fs->setFriend($friendship->getUser());
        $fs->setStatus(true);
        $friendship->getUser()->addFriendship($fs);
        $friendship->setStatus(true);
        $entityManager->persist($friendship);
        $entityManager->persist($fs);
        $entityManager->flush();

        return $this->redirectToRoute('show_profile', ['id' => $friendship->getUser()->getId()]);
    }

    #[Route('/friendship_list', name: 'requests', methods: ['GET'])]
    public function friendshipRequestList(LoggerInterface $logger): Response
    {
        $logger->info('Inside the controller!');
        $friendRequests = $this->getUser()->getFriendsWithMe();
        return $this->render('friends/friend_requests.html.twig', [
            'friendRequests' => $friendRequests,
        ]);
    }

    #[Route('/ajax/search-user', name: 'ajax_search_user', methods: ['GET', 'POST'])]
    public function searchUser(Request $request, UserRepository $userRepository): Response
    {
        $query = $request->get('search');
        $data = [];
        $users = $userRepository->searchByQuery($query)->getQuery()->getResult();
        foreach ($users as $value) {
            $data[] = ['id' => $value->getId(), 'text' => $value->getFirstName() . " " . $value->getLastName()];
        }
        $view = $this->renderView('users/_users_index.html.twig', [
            'pager' => $users
        ]);

        return new JsonResponse(['data' => $data, 'view' => $view]);
    }
}

templates/users/_delete_form.html.twig
<form method="post" action="{{ path('users_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/users/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/users/_users_index.html.twig
{% for user in pager %}
    <div class="col-md-4 mb-5 mb-md-0">
        <div class="card testimonial-card">
            <div class="card-up bg-secondary"></div>
            <div class="avatar mx-auto bg-white">
                {% if user.getAvatar() %}
                    <img src="{{ vich_uploader_asset(user.getAvatar) }}" alt="avatar"
                         class="rounded-circle img-fluid">
                {% else %}
                    <img src="https://www.kindpng.com/picc/m/24-248253_user-profile-default-image-png-clipart-png-download.png"
                         alt="" class="rounded-circle img-fluid">
                {% endif %}
            </div>
            <div class="card-body">
                <h4 class="mb-4">{{ user.firstName }} {{ user.lastName }}</h4>
                <hr>
                <div class="d-flex pt-1">
                    <a href="{{ path('show_profile', {'id': user.id}) }}" class="btn btn-info flex-grow-1">
                        View profile
                    </a>
                </div>
            </div>
        </div>
    </div>
{% else %}
    <div class="d-flex pt-1">
        <h2>no records found</h2>
    </div>
    <div class="d-flex pt-1">
        <a class="btn btn-sm btn-outline-info" href="{{ path('users_index') }}">All users</a>
    </div>
{% endfor %}

templates/users/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('users/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('users_index') }}">back to list</a>

    {{ include('users/_delete_form.html.twig') }}
{% endblock %}

templates/users/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <div class="input-group rounded" style="width: 25%">
        <input type="search" class="form-control" aria-label="Search"
               aria-describedby="search-addon" id="selUser" multiple="multiple"/>
        <span class="input-group-text border-1">
            <i class="fas fa-search"></i>
        </span>
    </div>

    <div class="row text-center mt-5">
        <div class="row text-center mt-5" id="users-index">
            {{ include('users/_users_index.html.twig') }}
        </div>
    </div>
    <div class="my-3" id="pagination">
        {% if pager|length > 4 %}
            {{ pagerfanta(pager) }}
        {% endif %}
    </div>

{% endblock %}

templates/users/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('users/_form.html.twig') }}

    <a href="{{ path('users_index') }}">back to list</a>
{% endblock %}

templates/users/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Username</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>First_name</th>
                <td>{{ user.firstName }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ user.lastName }}</td>
            </tr>
            <tr>
                <th>Gender</th>
                <td>{{ user.gender }}</td>
            </tr>
            <tr>
                <th>Birthday</th>
                <td>{{ user.birthday ? user.birthday|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('users_index') }}">back to list</a>

    <a href="{{ path('users_edit', {'id': user.id}) }}">edit</a>

    {{ include('users/_delete_form.html.twig') }}
{% endblock %}